---
- name: update security.yml with new agent token 
  connection: local
  run_once: yes
  lineinfile:
    dest: security.yml
    line: 'consul_acl_agent_token: {{ consul_agent_token }},'
    regexp: '.*consul_acl_agent_token.*'
    insertbefore: "^consul_acl_master_token"
  tags:
    - consul

- name: update acl file with agent token
  template:
    src: acl.json.j2
    dest: /etc/consul/acl.json
  tags:
    - consul

- include: reload_consul.yml
  
